#!/usr/bin/env python
# mad scientist diet planner

import sys
import os
import getopt
import re
import time

def comment(l):
	l = l.strip()
	c = None
	i = l.find('#')
	if i >= 0:
		c = l[i + 1:].strip()
		l = l[:i].strip()

	return (l, c)


def uname(s):
	return re.sub("^-?[0-9.]*", "", s)


class nval:
	def __init__(self, c, v = 0, f = 0):
		self.c = c
		self.v = v
		self.f = f


	def __div__(self, x):
		return nval(self.c / x, self.v / x, self.f / x)


class dbent:
	def __init__(self, v, c):
		self.v = v
		self.c = c


class Cal:
	def logfn(self):
		return "%s/.calcal.log" % os.environ["HOME"]


	def __init__(self, opts):
		self.units = {}
		self.eq = {}
		self.db = {}
		self.recipes = {}
		self.recipe = None
		self.summarize = None
		self.running = False
		self.store = {}
		self.tc = 0.0
		self.tv = 0.0
		self.tf = 0.0
		self.nr = -1
		self.ddelta = 0
		self.dmre = re.compile("^# [0-9]{4}(/[0-9]{2}){2}\n")
		self.daymark = None
		self.dtarget = None
		self.cw = {}
		self.cwloaded = False
		self.recpend = None
		self.newdb = []
		self.add_ig("overflow:	1/1\n")
		self.fcal("%s/.calories" % os.environ["HOME"])

		for i in opts:
			if i[0] == "-s":
				self.summarize = open(self.logfn(), "a")
				sys.stdout.write("# %s\n" % time.strftime("%F").replace("-","/"))
			elif i[0] == "-r":
				self.running = True
			elif i[0] == "-h":
				self.help()
			else:
				usage("unknown option %s" % i[0])


	def help(self):
		sys.stdout.write(usagemsg())
		sys.stdout.write("""\
-h - this message
-r - print running total
-s - summarize
""")
		sys.exit(0)


	def error(self, s):
		sys.stderr.write("%s:%d: %s\n" % (self.fn, self.nr, s))
		sys.exit(1)


	def unify(self, s):
		if s == "":
			self.error("amount missing")

		m = re.search("^(-?[0-9.]*)([^0-9].*)?", s)
		n = s[m.start(1):m.end(1)]
		u = s[m.start(2):m.end(2)]
		if n == "":
			n = 1.0
		else:
			n = float(n)
		if u in self.units:
			n *= self.units[u].v
		elif u != "g" and u != "ml" and u != "":
			self.error("weird unit %s\n" % u)

		return n


	def nify(self, s, a):
		c = None
		v = None
		f = None
		s = s.split()
		for i in s:
			if i.endswith("V"):
				if v != None:
					self.error("duplicate vegetable")
				v = self.unify(i[:-1])
			elif i.endswith("F"):
				if f != None:
					self.error("duplicate fruit")
				f = self.unify(i[:-1])
			else:
				if c != None:
					self.error("duplicate calorie")
				c = self.unify(i)

		if c == None:
			if v != None and f == None:
				c = v
				v = a
			elif v == None and f != None:
				c = f
				f = a
			else:
				self.error("missing calorie")

		if v == None:
			v = 0

		if f == None:
			f = 0

		return nval(float(c) / a, float(v) / a, float(f) / a);


	def cc2v(self, s):
		cv = s.strip().split('/')
		if len(cv) != 2:
			self.error("unrecognized calorie value")
		return self.nify(cv[0], self.unify(cv[1])) 


	def add_ig(self, l):
		(l, c) = comment(l)
		v = l.split(":")
		if len(v) != 2:
			return False

		self.db[v[0]] = dbent(self.cc2v(v[1]), c)
		return True


	def add_u(self, l):
		(l, c) = comment(l)
		v = l.split("=")
		if len(v) != 2:
			return False

		u = v[0].strip()
		if u[:1].isdigit():
			return False

		if u == "DELTA":
			self.ddelta = float(v[1].strip())
			return True

		self.units[u] = dbent(float(v[1].strip()), c)
		return True


	def add_e(self, l):
		(l, c) = comment(l)
		v = l.split("~")
		if len(v) != 2:
			return False

		u2 = self.unify(v[1].strip())
		u1 = v[0].strip()
		ig = u1
		m = re.search("[ 	]+", ig)
		ig = ig[m.end():]
		u1 = u1[:m.start()]
		un1 = uname(u1)
		u1 = self.unify(u1)

		self.eq[(ig, un1)] = dbent(u2 / u1, c)

		return True


	def badig(self, ig):
		if ig in self.db:
			return False

		self.error("unknown item %s\n" % ig)
		return True


	def loadcw(self):
		if self.cwloaded:
			return

		tcw = {}
		cwre = re.compile("^\\s*([0-9]\\S*)\\s+(\\S.*)-\\s*$")
		f = open(self.logfn(), "r")
		for l in f:
			if l == self.daymark:
				break
			m = cwre.search(l)
			if not m:
				continue
			ig = m.group(2)
			v = m.group(1)
			if ig in self.db:
				tcw[ig] = self.unify(v)
		f.close()

		for i in tcw.items():
			if not i[0] in self.cw:
				self.cw[i[0]] = i[1]


	def lcw(self, ig):
		if not ig in self.cw:
			self.loadcw()
			if not ig in self.cw:
				self.error("no last weighing for %s" % ig)
				return None

		return self.cw[ig]


	def rbegin(self, l):
		if not l.endswith("{"):
			return False

		if self.recpend != None:
			self.error("already in recipe")
			return False

		v = l[:-1].strip().split("/")
		if len(v) != 2:
			self.error("missing serving count")
			return False

		self.recpend = (v[0], int(v[1]), nval(self.tc, self.tv, self.tf))
		self.tc = 0
		self.tv = 0
		self.tf = 0

		return True


	def rend(self, l):
		if l != "}":
			return False

		if not self.recpend:
			self.error("not in recipe")
			return False

		(name, nserv, onv) = self.recpend
		self.recpend = None
		nv = nval(round(self.tc), round(self.tv), round(self.tf))
		self.db[name] = dbent(nv / nserv, "")
		self.newdb.append((name, nv, nserv))
		self.tc = onv.c
		self.tv = onv.v
		self.tf = onv.f
		return True


	def add_r(self, l):
		return self.rbegin(l) or self.rend(l)


	def xcal(self, l):
		if not self.daymark and self.dmre.match(l):
			self.daymark = l
			
		ol = l
		l = l.strip()
		if self.summarize:
			self.summarize.write(ol)

		if self.add_r(l):
			return

		if self.add_ig(l) or self.add_u(l) or self.add_e(l):
			if self.summarize:
				sys.stdout.write(ol)
			return


		l = re.sub("#.*", "", l).strip()
		if not l:
			return

		m = re.search("\\s+", l)
		if m:
			v = l[:m.start()]
			ig = l[m.end():]
		else:
			ig = l
			v = "1"

		if v.endswith("-"):
			v = v[:-1]
			if not self.badig(ig):
				self.store[ig] -= self.unify(v)
			return

		if v.endswith("+"):
			v = v[:-1]
			if not self.badig(ig):
				if not ig in self.store:
					self.store[ig] = 0
				self.store[ig] += self.unify(v)
			return

		if ig.endswith("+"):
			ig = ig[:-1]
			if not self.badig(ig):
				self.cw[ig] = self.unify(v)
			return

		cwval = None
		if ig.endswith("-"):
			ig = ig[:-1]
			if self.badig(ig):
				return
			cwval = self.lcw(ig)
			if cwval == None:
				return

		un = uname(v)
		ov = v
		v = self.unify(v)
		if cwval:
			v = cwval - v
		sig = ig.split("@")
		if len(sig) == 1:
			if self.badig(ig):
				return

			mv = self.db[ig].v
			ic = self.db[ig].c
			if ic == None:
				ic = ""
			if (ig, un) in self.eq:
				e = self.eq[(ig, un)]
				v *= e.v
				if e.c:
					ic += " " + e.c

				ic += "%s = %d" % (ov, v)
			if ig in self.store:
				self.store[ig] -= v
				if self.store[ig] < 0:
					v += self.store[ig]
					self.store[ig] = 0
		else:
			mv = self.cc2v(sig[1].strip())
			ig = sig[0].strip()
			ic = None

		if ic:
			ic = " (%s)" % ic.strip()
		else:
			ic = ""

		self.tc += v * mv.c
		self.tv += v * mv.v
		self.tf += v * mv.f
		if self.ddelta:
			if ig == "overflow":
				m = re.search("# target: ([0-9]+)", ol)
				if m:
					self.dtarget = int(m.group(1))
				else:
					self.dtarget = self.tc
			elif ig == "day":
				ic = " (%d veg %d fruit)" % \
					(round(self.tv), round(self.tf))
				self.tv = 0
				self.tf = 0
				if self.tc > 0 and self.dtarget:
					self.dtarget -= self.ddelta
					if self.dtarget < 0:
						self.dtarget = 0
					ic += " (net %d target %d offset %d)" % \
						(round(self.tc), self.dtarget,
							self.tc - self.dtarget)
		if not self.summarize:
			if self.running:
				sys.stdout.write("%8d " % self.tc)
			sys.stdout.write("%8.1f %8.1f %8.1f %s%s\n" % 
				 (v * mv.c, v, mv.c, ig, ic))


	def cal(self, f):
		self.nr = 0
		for l in f:
			self.nr += 1
			self.xcal(l)


	def fcal(self, fn):
		try:
			f = open(fn)
		except (IOError, OSError), err:
			sys.stderr.write("%s\n" % str(err))
			sys.exit(1)

		self.fn = fn
		self.cal(f)
		f.close()
		self.fn = None


	def finish(self):
		if self.summarize:
			for i in self.newdb:
				(name, nv, nserv) = i
				sys.stdout.write("%-16s%d" % ("%s:" % name, nv.c))
				if nv.v:
					sys.stdout.write(" %dV" % nv.v)
				if nv.f:	
					sys.stdout.write(" %dF" % nv.f)
				sys.stdout.write("/%d\n" % nserv)
			first = "\n"
			for i in self.store:
				sys.stdout.write("%s%d+\t%s\n" %
					(first, int(self.store[i] + 0.5), i))
				first = ""
			sys.stdout.write("\n%d\toverflow" %
				int(self.tc + 0.5))
			if self.dtarget:
				sys.stdout.write(" # target: %d" % self.dtarget)
			sys.stdout.write("\n")
		else:
			sys.stdout.write("%d" % round(self.tc))
			if self.tv > 0:
				sys.stdout.write(" %dV" % round(self.tv))
			if self.tf > 0:
				sys.stdout.write(" %dF" % round(self.tf))
			sys.stdout.write("\n")


def usagemsg():
	if len(sys.argv) > 0:
		prog = sys.argv[0]
	else:
		prog = "calcal"
	return "usage: %s [-hrs] [file]\n" % prog


def usage(s = None):
	if s:
		sys.stderr.write("%s\n" % s)
	sys.stderr.write(usagemsg())
	sys.exit(2)



try:
	(opts, args) = getopt.getopt(sys.argv[1:], "hrs")
except getopt.GetoptError, err:
	usage(str(err))

cc = Cal(opts)

if len(args) < 1:
	cc.fn = "stdin"
	cc.cal(sys.stdin)
elif len(args) > 1:
	usage()
else:
	cc.fcal(args[0])

cc.finish()
